version: '3.8'

services:
  auth-api-microservice:
    build: ..
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
    container_name: auth-api
    networks:
      - abc-call-network

networks:
  abc-call-network:
    external: true